### ISSUE TITLE
Address book shows up empty in Thunderbird

### ISSUE THREAD

**Issue by LogicalDash** [etesync/etesync-dav#1]
I got etesync-dav to run (in Python 3.6 -- this should be listed as a requirement, if indeed it's meant to be) but the CardDAV address book always showed up blank in Thunderbird. To diagnose this I ran example.py with all my credentials and remote server http://etesync.com and it gave me error 405, which might also be why the address book is blank.

Is your implementation of the EteSync API out of date, perhaps?

**Comment by tasn** [comment]
Hey,

I think I know what's going on. Here's a combination of questions and suggestions for fixing it:

1. Why is python 3.6 a requirement? Python 3 is if memory serves, but not specifically 3.6. Or is that what you meant? Where should I mark it (I'm new to setuptools).
2. Have you followed the instructions in the readme for Thunderbird? (sounds like you have, just double checking).
3. I need to update the readme to include this, but the server should be: https://api.etesync.com - note the https.
4. 405 means "method not allowed". I suspect you got it because you used http which was redirected to https, and then made the post request a get request, which is not allowed. Changing to the https address above would fix it.
5. Please take a look at the output of etesync-dav to see if any errors are reported there.
6. There is currently an issue with etesync-dav and contact groups. Are you using these? The issue is in a third party, to which I already sent a PR which was just merged last night. You could install https://github.com/eventable/vobject from git which will include my fix. Otherwise you can wait for a bit until they make a release.

Assuming you are using the thunderbird cardbook extension, it should just work once you have etesync-dav up and running, so please let me know if you have any additional issues. Etesync-dav is very recent and may have issues.

**Comment by LogicalDash** [comment]
Well, it doesn't work with 3.5 because you rely on ``random.choices`` which is a 3.6 addition...

**Comment by tasn** [comment]
Oops, thanks! I'll fix this in a moment. Is the other issue resolved? May I close it?

**Comment by LogicalDash** [comment]
``ERROR: Invalid configuration: Invalid section 'etesync_storage' in config``

**Comment by tasn** [comment]
Does etesync-dav print out any errors?
Do you use contact groups?
Could you try creating a new journal with just one contact and see if that one works?
What exactly are the settings you put in thunderbird, and are you using the CardBook extension as recommended?

**Comment by LogicalDash** [comment]
* It doesn't print any errors
* I guess I'm using contact groups, yeah, but I did install the latest master of vobject like you said
* Tried this and it gave me this error on the command line:
```
[7f965b324700] ERROR: An exception occurred during request:
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/sanotehu/.local/lib/python3.6/site-packages/radicale/__init__.py", line 425, in __call__
    environ, base_prefix, path, user)
  File "/home/sanotehu/.local/lib/python3.6/site-packages/radicale/__init__.py", line 686, in do_PUT
    path, items, {"tag": tag})
  File "/home/sanotehu/.local/lib/python3.6/site-packages/radicale_storage_etesync/__init__.py", line 299, in create_collection
    href = self._find_available_file_name(
AttributeError: 'CollectionCopy' object has no attribute '_find_available_file_name'
```
* I'm using CardBook and I changed the vCard version to 4.0, everything else is default.

**Comment by tasn** [comment]
I released a version that works with python < 3.6 too.
If you are using latest master vobject, it should work, so let's assume the problem is not with groups.
Just to understand the error you just reported, you created a new journal in the etesync app, added a contact, synced, and then tried adding it again to thunderbird? Either way, nvm this test, wouldn't help anyway, I'm just interested to know why it failed.

As for the original issue, maybe try clearing the local etesync config and cache by removing: .config/etesync-dav

Maybe it got corrupted for some reason when failing with 3.5, though I really doubt that's the case.

**Comment by tasn** [comment]
Btw, do calendar events work?

**Comment by LogicalDash** [comment]
I can't seem to get etesync-dav to run at all now -- it keeps giving me that
```
ERROR: Invalid configuration: Invalid section 'etesync_storage' in config
```
And I guess it doesn't actually make a difference which Python version I use -- maybe it was actually because I'd inadvertently installed different Radicale versions in the different Python versions' site-packages.

**Comment by LogicalDash** [comment]
I worked around the problem in the previous comment by installing Radicale 2.0.0 instead of the latest. I guess you need to keep your settings elsewhere for compatibility,

**Comment by LogicalDash** [comment]
No luck on the calendar, though. I log in just fine but there are no events, and I know there should be several.

**Comment by LogicalDash** [comment]
[Have  a log](https://gist.github.com/LogicalDash/c3a37095fa0834e63b2c85ca8595812d)

**Comment by tasn** [comment]
Try installing pytz (I see a related error in the log), and let me know if that fixes it. Again, you may have to clear the cache directory to make it work (they shouldn't be needed, but who knows).

Please let me know if that fixes it for you.

**Comment by LogicalDash** [comment]
Tried it, made no difference.

[Here's a shorter log](https://gist.github.com/LogicalDash/b700ca30824386af881042b04bea2be0) with just what I get when I try to sync a calendar.

**Comment by LogicalDash** [comment]
Note that it took a pretty long time for the log to get that far; I had the impression that it was done while it looked like [this](https://gist.github.com/LogicalDash/b700ca30824386af881042b04bea2be0/c90f7b08906af21037168830416fc2570fe0da4c).

**Comment by tasn** [comment]
The first one shows a 401, which means you used the wrong username/password, and anyhow, judging by the user agent, it's a log for cardbook.

With calendars on thunderbird you need to use the full journal path (just making sure you remember this limitation, though it looks like you do). Does thunderbird print any errors? Were there any configuration options you had to choose?

I just tested with lightning 5.4.2.1 and thunderbird 52.2.1.
Url: http://localhost:37358/me@etesync.com/b71504d4fef88e685472bb7a77f10c338d7e6bef9041994e3809e7622727f5a3/

Everything works.

Got any ideas what you may be doing that is different?

**Comment by LogicalDash** [comment]
The calendar randomly started working for some reason...?

Anyway, the error when I try to validate the CardBook login is:
```
2017.07.10 17:49:19:895 : Validation module : Synchronization failed (step : validateWithoutDiscovery, url : http://localhost:37358/zack@zacharyspector.com/, status : 0)
```

**Comment by LogicalDash** [comment]
I got it working by specifying the big long hexadecimal ID of the collection, which had changed; I used the one the etesync-dav log gave me. [Here are the etesync-dav logs for when I do not specify the collection.](https://gist.github.com/LogicalDash/f017a9a7dd93918b0d3dfe04706ff92d)

**Comment by tasn** [comment]
Calendar randomly started to work: there's a small UX issue that may be related. Big syncs (for example the first one) may take some time and there's currently no easy way to show that to the user. I wonder if it was just downloading everything and thus thunderbird timed out and showed nothing. I'd expect however thunderbird to show an error for the timeout. Not sure if that was what happened in your case.

For me it works without specifying the collection. I literally just tested this, so it's definitely not required. Collection UIDs don't just change. I'm not sure what happened in your case, but if the log prints out the correct UID it means that it should work, like it had before, so I'm really not sure what happened for you there.

**Comment by LogicalDash** [comment]
I guess this is a Could Not Reproduce.

**Comment by tasn** [comment]
Oh wow, sorry, I thought I replied already! I'm willing to continue investigating it if you are.

While looking around the other day I saw someone mentioning Radicale (the server we use for the proxy) is sometimes funky with Thunderbird. I wonder if that's the issue you're experiencing.
